name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json

  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10.7'

    - name: Build Docker Image
      run: docker build -f Dockerfile -t myapp:latest .

    - name: Push Docker Image to DockerHub
      run: |
       echo ${{ secrets.REPO_PWD }} | docker login -u ${{ secrets.REPO_USER }} --password-stdin
       docker tag myapp:latest ${{ secrets.REPO_USER }}/myapp:latest
       docker push ${{ secrets.REPO_USER }}/myapp:latest

    - name: Verify Pushed Docker Image
      run: docker pull ${{ secrets.REPO_USER }}/myapp:latest

    - name: List Docker Scout Temp Directory
      run: ls -l /tmp/docker-scout || echo "Directory does not exist"

    - name: Fix Permissions for Temp Directory
      run: mkdir -p /tmp/docker-scout && chmod -R 777 /tmp/docker-scout

    - name: Docker Scout Quickview
      uses: docker/scout-action@v1.0.9
      env:
        DOCKER_SCOUT_TMPDIR: /github/workspace/tmp
      with:
        dockerhub-user: ${{ secrets.REPO_USER }}
        dockerhub-password: ${{ secrets.REPO_PWD }}
        image: ${{ secrets.REPO_USER }}/myapp:latest
        command: quickview
        only-severities: critical,high
        sarif-file: scout-quickview.sarif
